/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.picasyfijas;

import co.appreactor.picasyfijas.modelo.Palabras;
import co.appreactor.picasyfijas.negocio.Comparador;
import java.util.Random;

/**
 *
 * @author Lord_Nightmare
 */
public class Principal extends javax.swing.JFrame {

    private String palabra;
    private final String mensajePicas = "Picas: ";
    private final String mensajeFijas = "Fijas: ";
    private int intentos;
    private Comparador comp;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        lblMensaje.setText("");
        lblPalabra.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPalabra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIntentar = new javax.swing.JButton();
        btnRendir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblPicas = new javax.swing.JLabel();
        lblFijas = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblPalabra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("lblTitulo");

        btnIntentar.setText("Intentar");
        btnIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentarActionPerformed(evt);
            }
        });

        btnRendir.setText("Rendirse");
        btnRendir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Juego");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblPicas.setText("Picas: {}");

        lblFijas.setText("Fijas: {}");

        lblMensaje.setText("Mensaje");

        lblPalabra.setText("Palabra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRendir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntentar))
                    .addComponent(lblPicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFijas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFijas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPalabra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntentar)
                    .addComponent(btnRendir)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        palabra = Palabras.MIS_PALABRAS[new Random().nextInt((Palabras.MIS_PALABRAS.length - 1) - 0 + 1)];
        comp = new Comparador(palabra);
        intentos = 10;
        System.out.println("Palabra: " + palabra);
        btnNuevo.setEnabled(false);
        btnIntentar.setEnabled(true);
        btnRendir.setEnabled(true);
        txtPalabra.setText("");
        lblMensaje.setText("");
        lblPalabra.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRendirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirActionPerformed
        lblMensaje.setText("Descuida, No todos pueden ser triunfadores");
        lblPalabra.setText("La palabra a adivinar era: " + palabra);
        btnNuevo.setEnabled(true);
        btnIntentar.setEnabled(false);
        btnRendir.setEnabled(false);
    }//GEN-LAST:event_btnRendirActionPerformed

    private void btnIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentarActionPerformed
        if (intentos < 1) {
            lblMensaje.setText("Has perdido, no tienes mas intentos");
            btnNuevo.setEnabled(true);
            btnIntentar.setEnabled(false);
            btnRendir.setEnabled(false);
            return;
        }
        if (!palabra.equalsIgnoreCase(txtPalabra.getText())) {
            comp.setPalabraComparar(txtPalabra.getText());
            lblPicas.setText(mensajePicas + comp.obtenerPicas());
            lblFijas.setText(mensajeFijas + comp.obtenerFijas());
            intentos--;
            return;
        }
        lblMensaje.setText("Felicidades, has ganado!");
        btnNuevo.setEnabled(true);
        btnIntentar.setEnabled(false);
        btnRendir.setEnabled(false);
    }//GEN-LAST:event_btnIntentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntentar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRendir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFijas;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPalabra;
    private javax.swing.JLabel lblPicas;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
